version: '3.8'
services:
  server-a:
    build: ../server-a
    environment:
      - SERVER_PORT=8080
      - TARGET_URL=http://server-b:8081/api/b
      - SERVER_TOMCAT_THREADS_MAX=1
      - SPRING_THREADS_VIRTUAL_ENABLED=false

  server-b:
    build: ../server-b
    environment:
      - SERVER_PORT=8081
      - TARGET_URL=http://server-a:8080/api/a/callback